### ISSUE TITLE
Can not update to version 0.1.5, Octoprint 1.6

### ISSUE THREAD

**Issue by nionio6915** [Salandora/OctoPrint-EEPROM-Repetier#16]
Attempts to update plugin result in erroring out.  I am doing my best to try to self-diagnose and fix it but I am getting no where. 

Lines from Octoprint log: 

2021-05-01 20:22:39,606 - octoprint.plugins.softwareupdate - INFO - Starting update of eeprom_repetier to 0.1.5...
2021-05-01 20:22:45,628 - octoprint.plugins.softwareupdate - ERROR - Update of eeprom_repetier can not be performed, please also check plugin_softwareupdate_console.log for possible causes of this
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/__init__.py", line 1828, in _perform_update
    target, populated_check, target_version, log_cb=self._log, online=online
  File "/home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/updaters/pip.py", line 144, in perform_update
    "Error while executing pip install", (stdout, stderr)
UpdateError: Error while executing pip install

Lines from plugin_software_update_console.log:

2021-05-01 20:22:39,623   /home/pi/oprint/bin/python2 -m pip --disable-pip-version-check install https://github.com/Salandora/OctoPrint-EEPROM-Repetier/archive/0.1.5.zip --no-cache-dir
2021-05-01 20:22:43,137 > Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
2021-05-01 20:22:43,139 > Collecting https://github.com/Salandora/OctoPrint-EEPROM-Repetier/archive/0.1.5.zip
2021-05-01 20:22:43,141 > Downloading https://github.com/Salandora/OctoPrint-EEPROM-Repetier/archive/0.1.5.zip
2021-05-01 20:22:45,613 > Complete output from command python setup.py egg_info:
2021-05-01 20:22:45,614 > Found packages: set([u'octoprint_eeprom_repetier'])
2021-05-01 20:22:45,615 > error in OctoPrint-EEprom-Repetier setup command: package_data must be a dictionary mapping package names to lists of wildcard patterns
2021-05-01 20:22:45,615 > 
2021-05-01 20:22:45,616 > ----------------------------------------
2021-05-01 20:22:45,625 ! Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-S7Pvui/
2021-05-01 20:22:45,686   /home/pi/oprint/bin/python2 -m pip --disable-pip-version-check install https://github.com/kantlivelong/OctoPrint-PSUControl/archive/1.0.5.zip --no-cache-dir

**Comment by Wotsamatter** [comment]
Possibly caused by forcing unicode strings in the setup.py file, which causes compatibility problems with older versions of setuptools on Python2.7 pip2.  The import unicode_literals has been removed and a new release 0.1.6 created.  Please use this newer version instead.
